"$schema" = 'https://starship.rs/config-schema.json'

format = """
[â–‘â–’â–“](#a3aed2)\
[ $os ](bg:#a3aed2 fg:#090c0c)\
[î‚´](bg:#769ff0 fg:#a3aed2)\
$directory\
[î‚´](fg:#769ff0 bg:#394260)\
$git_branch\
[î‚´](fg:#394260 bg:#212736)\
$nodejs\
$rust\
$golang\
$php\
$camel\
$swift\
$bun\
$aws\
$terraform\
$buf\
$c\
$conda\
$dart\
$docker_context\
$elixir\
$elm\
$haskell\
$haxe\
$java\
$julia\
$lua\
$python\
$rlang\
$ruby\
$scala \
$package \
[î‚´ ](fg:#1d2230)\
\n$shell\
$character"""

right_format = """
[î‚¶](fg:#1d2230)\
$status\
[$git_state](bg:#a3aed2 fg:#a3aed2)\
[$git_status](bg:#a3aed2 fg:#a3aed2)\
[î‚¶](fg:#769ff0 bg:#212736)\
$username\
$hostname\
[î‚¶](bg:#769ff0 fg:#a3aed2)\
[ ](bg:#a3aed2 fg:#a3aed2)
[$cmd_duration $time $battery](bg:#1d2230 fg:#a3aed2)\
[â–“â–’â–‘](#a3aed2)\
"""

continuation_prompt = 'â–¶â–¶ '

scan_timeout = 10

[character]
success_symbol = '[Î»](bold green) '
error_symbol = '[âœ—](bold red) '
vimcmd_symbol = "[â®](bold green)"

[status]
style = "fg:red bg:#1d2230"
format = '[$status ]($style)'
disabled = false

[username]
format = "[$user]($style)"
style_user = "fg:#e3e5e5 bg:#769ff0"
style_root = "fg:#ff0000 bg:#769ff0"
show_always = true

[hostname]
style = "fg:#e3e5e5 bg:#769ff0"
format = "[@$hostname ]($style)"
trim_at = "-"
ssh_only = false
disabled = false

[shell]
fish_indicator = ''
powershell_indicator = 'PS:'
unknown_indicator = '?:'
nu_indicator = 'nu:'
bash_indicator = '$:'
cmd_indicator = 'cmd:'
style = 'green bold'
disabled = false

[cmd_duration]
min_time = 500
format = "[[ âŒ› $duration](fg:yellow bg:#1d2230)]($style)"

[time]
disabled = false
time_format = "%R"                                     # Hour:Minute Format
style = "bg:#1d2230"
format = '[[ ïº $time](fg:#a0a9cb bg:#1d2230)]($style)'

[battery]
disabled = false
full_symbol = "ï•¸"
charging_symbol = "ï–‡ "
discharging_symbol = "ï–Œ "
unknown_symbol = "ï–"
empty_symbol = "ï–"
format = "[$symbol$percentage ]($style)"
[[battery.display]]
threshold = 10
style = "fg:#a0a9cb bg:#1d2230"
[[battery.display]]
threshold = 20
style = "bg:#DE935F fg:#111111"

[directory]
style = "fg:#e3e5e5 bg:#769ff0"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "â€¦/"
read_only = "ğŸ”’"
read_only_style = "red"

[directory.substitutions]
"Documents" = "ïœ™"
"Downloads" = "ï€™"
"Music" = "ï€"
"Pictures" = "ï€¾"
"Movies" = "ï—¼"
"Sources" = "ï„¡"
"~" = "ï‘­"
"/" = " î‚± "

[git_branch]
symbol = "ï˜"
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[git_commit]
format = "[ $tag ]($style)"
style = "bold green"

[git_status]
format = '([\[$all_status$ahead_behind\] ]($style))'
style = "fg:#769ff0 bg:#1d2230"
conflicted = "="
ahead = "â‡¡${count} "
behind = "â‡£${count} "
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
untracked = "?${count} "
stashed = "$${count} "
modified = "!${count} "
staged = "+${count} "
renamed = "Â»${count} "
deleted = "âœ˜${count} "
disabled = false

[git_state]
rebase = "REBASING"
merge = "MERGING"
revert = "REVERTING"
cherry_pick = "CHERRY-PICKING"
bisect = "BISECTING"
am = "AM"
am_or_rebase = "AM/REBASE"
style = "bold yellow"
format = '\([$state( $progress_current/$progress_total)]($style)\) '
disabled = false

[hg_branch]
symbol = "ï˜ "
style = "bold purple"
format = "on [$symbol$branch]($style) "

[bun]
symbol = ' î‰ '
style = "bg:#212736"
#detect_files = ["package.json"]
#detect_folders = ["node_modules"]
format = '[[$symbol($version) ](fg:#769ff0 bg:#212736)]($style)'

[nodejs]
symbol = "ï¢˜"
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'
detect_files = ["package.json", ".node-version"]
detect_folders = ["node_modules"]

[rust]
symbol = "î¨"
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[swift]
symbol = "î• "
style = "fg:#a0a9cb bg:#1d2230"
format = '[[ $symbol $version ](fg:#a0a9cb bg:#1d2230)]($style)'
disabled = false

[golang]
symbol = "ï³‘"
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[php]
symbol = "î˜ˆ"
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[perl]
symbol = "î™¾ "
style = "fg:#a0a9cb bg:#1d2230"
format = '[[ $symbol $version ](fg:#a0a9cb bg:#1d2230)]($style)'
disabled = false

[aws]
# disabled = true
symbol = "îŒ½ "
style = "bg:#e4c180"
format = '[[î‚´](bg:#e4c180 fg:#A6A6A6)$symbol$profile(\($region\))[î‚´](bg:#A6A6A6 fg:#e4c180)]($style)'

[terraform]
symbol = "î® "
style = "fg:#a0a9cb bg:#1d2230"
format = '[[ $symbol $version ](fg:#a0a9cb bg:#1d2230)]($style)'
disabled = false

[cmake]
# disabled = true
# symbol = "ï¨µ" # alternate
symbol = "ï¨¶"
style = "bg:#57686B fg:#EEEEEE"
format = "[[î‚´](bg:#57686B fg:#A6A6A6)$symbol$version[î‚´](bg:#A6A6A6 fg:#57686B)]($style)"

[buf]
symbol = " ï’ "

[c]
symbol = " î˜ "

[conda]
disabled = false
symbol = "ï„Œ "
style = "bg:#a4b595 fg:#111111"
ignore_base = true
truncation_length = 1
format = "[[î‚´](bg:#a4b595 fg:#A6A6A6)$symbol$environment[î‚´](bg:#A6A6A6 fg:#a4b595)]($style)"

[crystal]
# disabled = true
symbol = "ïˆ™ "
style = "bg:#EEEEEE fg:#111111"
format = "[[î‚´](bg:#EEEEEE fg:#A6A6A6)$symbol$version[î‚´](bg:#A6A6A6 fg:#EEEEEE)]($style)"

[dart]
# disabled = true
symbol = "î˜ " # original
# symbol = "ï¯‘ " # clearer
style = "bg:#32BBF9 fg:#111111"
format = "[[î‚´](bg:#32BBF9 fg:#A6A6A6)$symbol$version[î‚´](bg:#A6A6A6 fg:#32BBF9)]($style)"

[docker_context]
symbol = " ïŒˆ "
format = "[$symbol$context]($style) "
style = "blue bold"
only_with_files = true
detect_files = ["docker-compose.yml", "docker-compose.yaml", "Dockerfile"]
detect_folders = []
disabled = false

[elixir]
symbol = " î‰µ "

[elm]
symbol = " î˜¬ "

[haskell]
symbol = " î· "

[haxe]
symbol = " âŒ˜ "

[java]
symbol = " î‰– "

[julia]
symbol = " î˜¤ "

[lua]
symbol = " î˜  "

[memory_usage]
symbol = " ï¡š "

[nim]
symbol = " ïš¤ "

[python]
symbol = " î˜† "
#pyenv_version_name = true
format = '[${symbol}python (${version} )(\($virtualenv\) )]($style)'
style = "bold yellow"
pyenv_prefix = "venv "
python_binary = ["./venv/bin/python", "python", "python3", "python2"]
detect_extensions = ["py"]
version_format = "v${raw}"

[rlang]
symbol = " ï³’ "

[ruby]
symbol = " î‘ "
style = "fg:#a0a9cb bg:#1d2230"
format = '[[ $symbol $version ](fg:#a0a9cb bg:#1d2230)]($style)'
disabled = false

[scala]
symbol = " îœ· "

[os]
format = "[$symbol]($style)"
style = "fg:#769ff0 bg:#1d2230"
disabled = false

[os.symbols]
Alpaquita = " îª¢ "
Alpine = " ïŒ€ "
Amazon = " ï‰° "
Android = " ï…» "
Arch = " ïŒƒ "
Artix = " ïŒŸ "
CentOS = " ïŒ„ "
Debian = " ïŒ† "
DragonFly = " îŠ "
Emscripten = " ïˆ… "
EndeavourOS = " ï†— "
Fedora = " ïŒŠ "
FreeBSD = " ïŒŒ "
Garuda = " ï¯‘ "
Gentoo = " ïŒ "
HardenedBSD = " ï²Š "
Illumos = " ïœ· "
Linux = " ïŒš "
Mabox = " î¬© "
Macos = " ïŒ‚ "
Manjaro = " ïŒ’ "
Mariner = " ï‡ "
MidnightBSD = " ï†† "
Mint = " ïŒ "
NetBSD = " ï€¤ "
NixOS = " ïŒ“ "
OpenBSD = " ïœ¹ "
openSUSE = " ïŒ” "
OracleLinux = " ï ¶ "
Pop = " ïŒª "
Raspbian = " ïŒ• "
Redhat = " ïŒ– "
RedHatEnterprise = " ïŒ– "
Redox = " ï”— "
Solus = " ï´± "
SUSE = " ïŒ” "
Ubuntu = " ïŒ› "
Unknown = " ïˆ­ "
Windows = " ï¡± "

[package]
symbol = "ï£– "
style = "fg:#a0a9cb bg:#1d2230"
format = '[[ $symbol $version ](fg:#a0a9cb bg:#1d2230)]($style)'
disabled = false
